name: Terraform Twingate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/twingate

    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TF_VAR_TWINGATE_API_TOKEN: ${{ secrets.TWINGATE_API_TOKEN }}
      TF_VAR_TWINGATE_ADMIN_USER_ID: ${{ secrets.TWINGATE_ADMIN_USER_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_JSON_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode -out=tfplan || exit 0

      - name: Terraform Apply (if changes)
        if: steps.plan.outcome == 'success'
        run: terraform apply -auto-approve tfplan
